spring:
  application:
    name: springboot-graphql
  servlet:
    multipart:
      max-file-size: 2MB

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 100
    exception-handlers-enabled: true
    tracingEnabled: true
  playground:
    headers:
      Authorization: Bearer TOKEN
      user_id: IDJ|Elias
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
  annotations:
    base-package: com.example.springbootgraphql
  schema-strategy: annotations

  # enabled: true

voyager:
  enabled: true

logging:
  pattern:
    console: -%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%X{correlation_id}){red} %m%n%wEx
