spring:
  application:
    name: springboot-graphql

server:
  http2:
    enabled: true

graphql:
  servlet:
    # avoid recursion
    maxQueryDepth: 5
  playground:
    settings:
      request.credentiels: omit
